services:
  weewx-rtldavis:
    container_name: weewx-rtldavis
    image: weatheredscientist/weewx-rtldavis:latest
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /volume1/docker/weewx-rtldavis/weewx-data:/opt/weewx-data
      - /volume1/docker/weewx-rtldavis/logs:/var/log/weewx
